<html>
<head>
<title>5 things you don’t know about try-catch-finally in JavaScript</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">关于JavaScript中的try-catch-finally，你不知道的5件事</h1>
<blockquote>原文：<a href="https://levelup.gitconnected.com/5-things-you-dont-know-about-try-catch-finally-in-javascript-5d661996d77c?source=collection_archive---------1-----------------------#2019-12-16">https://levelup.gitconnected.com/5-things-you-dont-know-about-try-catch-finally-in-javascript-5d661996d77c?source=collection_archive---------1-----------------------#2019-12-16</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><div class=""><h2 id="7106" class="pw-subtitle-paragraph jn ip iq bd b jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke dk translated">了解如何在JavaScript中执行try-catch-finally</h2></div><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi kf"><img src="../Images/a3a47954ef4ebd077f906b480095bf57.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*ycowoRYkidGSKBE42TOcVg.jpeg"/></div></div><figcaption class="kr ks gj gh gi kt ku bd b be z dk translated">基思·约翰斯顿在<a class="ae kv" href="https://unsplash.com/s/photos/try-catch?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上的照片</figcaption></figure><p id="47a8" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">try-catch-finally用于处理运行时错误，防止它们停止程序的执行。</p><div class="ls lt gp gr lu lv"><a rel="noopener  ugc nofollow" target="_blank" href="/everything-you-need-to-know-about-error-handling-in-javascript-caa6c066274d"><div class="lw ab fo"><div class="lx ab ly cl cj lz"><h2 class="bd ir gy z fp ma fr fs mb fu fw ip bi translated">关于Javascript中的错误处理，您需要知道的一切</h2><div class="mc l"><h3 class="bd b gy z fp ma fr fs mb fu fw dk translated">了解如何在Javascript中处理异常。</h3></div><div class="md l"><p class="bd b dl z fp ma fr fs mb fu fw dk translated">levelup.gitconnected.com</p></div></div><div class="me l"><div class="mf l mg mh mi me mj kp lv"/></div></div></a></div><h1 id="e62c" class="mk ml iq bd mm mn mo mp mq mr ms mt mu jw mv jx mw jz mx ka my kc mz kd na nb bi translated">1.try或catch块中的Return语句</h1><p id="65e9" class="pw-post-body-paragraph kw kx iq ky b kz nc jr lb lc nd ju le lf ne lh li lj nf ll lm ln ng lp lq lr ij bi translated">如果我们有一个<code class="fe nh ni nj nk b">finally</code>块，那么<code class="fe nh ni nj nk b">try</code>和<code class="fe nh ni nj nk b">catch</code>块中的<code class="fe nh ni nj nk b">return</code>语句不会被执行。它总是会撞上<code class="fe nh ni nj nk b">finally</code>的阻碍。</p><pre class="kg kh ki kj gt nl nk nm nn aw no bi"><span id="cd0a" class="np ml iq nk b gy nq nr l ns nt">function test() {</span><span id="f59e" class="np ml iq nk b gy nu nr l ns nt">try {</span><span id="f4cd" class="np ml iq nk b gy nu nr l ns nt">return 10;</span><span id="5e44" class="np ml iq nk b gy nu nr l ns nt">} <strong class="nk ir">finally</strong> {</span><span id="7d07" class="np ml iq nk b gy nu nr l ns nt">console.log("finally");</span><span id="4ac9" class="np ml iq nk b gy nu nr l ns nt">return 1;<br/>   }</span><span id="07ac" class="np ml iq nk b gy nu nr l ns nt">}</span><span id="506c" class="np ml iq nk b gy nu nr l ns nt">console.log( test() ); // finally 1</span></pre><p id="b9e9" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">示例2:</p><pre class="kg kh ki kj gt nl nk nm nn aw no bi"><span id="e676" class="np ml iq nk b gy nq nr l ns nt">function test() {</span><span id="e88c" class="np ml iq nk b gy nu nr l ns nt">try {     <br/>    return 10;<br/>    throw "error"; // this is not executed, control goes to finally<br/>  } <strong class="nk ir">catch</strong> {<br/>    console.log("<strong class="nk ir">catch</strong>"); <br/>    return 1;<br/>  } finally { <br/>    console.log("finally");<br/>    return 1000;<br/>  }</span><span id="a7b6" class="np ml iq nk b gy nu nr l ns nt">}</span><span id="17d6" class="np ml iq nk b gy nu nr l ns nt">console.log( test() ); // finally 1000</span></pre><h1 id="d1ea" class="mk ml iq bd mm mn mo mp mq mr ms mt mu jw mv jx mw jz mx ka my kc mz kd na nb bi translated">2.try块中声明的变量在catch或finally块中不可用</h1><p id="cf38" class="pw-post-body-paragraph kw kx iq ky b kz nc jr lb lc nd ju le lf ne lh li lj nf ll lm ln ng lp lq lr ij bi translated">如果我们使用<code class="fe nh ni nj nk b">let</code>或<code class="fe nh ni nj nk b">const</code>在<code class="fe nh ni nj nk b">try</code>块中声明一个变量，它将不能被<code class="fe nh ni nj nk b">catch</code>或<code class="fe nh ni nj nk b">finally</code>使用。这是因为这些变量声明是块范围的。</p><pre class="kg kh ki kj gt nl nk nm nn aw no bi"><span id="9171" class="np ml iq nk b gy nq nr l ns nt">try {<br/>   <br/>    let a = 10;</span><span id="c212" class="np ml iq nk b gy nu nr l ns nt">    throw "a is block scoped ";</span><span id="411d" class="np ml iq nk b gy nu nr l ns nt">} catch(e) {<br/>    <br/>    console.log("Reached catch");</span><span id="09a4" class="np ml iq nk b gy nu nr l ns nt">    console.log(a); // Reference a is no defined</span><span id="4962" class="np ml iq nk b gy nu nr l ns nt">}</span></pre><p id="844d" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">但是如果我们使用<code class="fe nh ni nj nk b">var</code>而不是<code class="fe nh ni nj nk b">let</code>或<code class="fe nh ni nj nk b">const</code>，那么它将在<code class="fe nh ni nj nk b">catch</code>内部可用，因为<code class="fe nh ni nj nk b">var</code>是函数作用域，声明将被提升。</p><pre class="kg kh ki kj gt nl nk nm nn aw no bi"><span id="2d27" class="np ml iq nk b gy nq nr l ns nt">try {<br/>   <br/>    var a = 10;</span><span id="a2f0" class="np ml iq nk b gy nu nr l ns nt">    throw "a is function scoped ";</span><span id="e554" class="np ml iq nk b gy nu nr l ns nt">} catch(e) {<br/>    <br/>    console.log("Reached catch");</span><span id="fa05" class="np ml iq nk b gy nu nr l ns nt">    console.log(a); // 10</span><span id="bdcf" class="np ml iq nk b gy nu nr l ns nt">}</span></pre><h1 id="9e0c" class="mk ml iq bd mm mn mo mp mq mr ms mt mu jw mv jx mw jz mx ka my kc mz kd na nb bi translated">3.无错误详细信息的捕获</h1><p id="6248" class="pw-post-body-paragraph kw kx iq ky b kz nc jr lb lc nd ju le lf ne lh li lj nf ll lm ln ng lp lq lr ij bi translated">在ES2019中，<code class="fe nh ni nj nk b">catch</code>块的参数是可选的。</p><pre class="kg kh ki kj gt nl nk nm nn aw no bi"><span id="2ab8" class="np ml iq nk b gy nq nr l ns nt">try {<br/>   // code with bug;</span><span id="7f31" class="np ml iq nk b gy nu nr l ns nt">} catch {</span><span id="09e9" class="np ml iq nk b gy nu nr l ns nt">   // catch without exception argument</span><span id="892f" class="np ml iq nk b gy nu nr l ns nt">}</span></pre><h1 id="2c51" class="mk ml iq bd mm mn mo mp mq mr ms mt mu jw mv jx mw jz mx ka my kc mz kd na nb bi translated">4.try…catch在<code class="fe nh ni nj nk b">setTimeOut</code>上不起作用</h1><p id="708f" class="pw-post-body-paragraph kw kx iq ky b kz nc jr lb lc nd ju le lf ne lh li lj nf ll lm ln ng lp lq lr ij bi translated">如果一个异常发生在“预定的”代码中，比如<code class="fe nh ni nj nk b">setTimeout</code>，那么<code class="fe nh ni nj nk b">try..catch</code>不会捕捉到它。</p><pre class="kg kh ki kj gt nl nk nm nn aw no bi"><span id="5af1" class="np ml iq nk b gy nq nr l ns nt">function callback() {</span><span id="17ec" class="np ml iq nk b gy nu nr l ns nt">    // error code</span><span id="84ff" class="np ml iq nk b gy nu nr l ns nt">}</span><span id="d05d" class="np ml iq nk b gy nu nr l ns nt">function test() {</span><span id="9d56" class="np ml iq nk b gy nu nr l ns nt">   <!-- -->try {<br/>      setTimeout( callback , 1000);<br/>   } catch (e) {<br/>      console.log( "not executed" );<br/>   }</span><span id="ad05" class="np ml iq nk b gy nu nr l ns nt">}</span></pre><p id="d3c4" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">为了处理这个问题，我们需要在<code class="fe nh ni nj nk b">setTimeOut</code>回调中添加<code class="fe nh ni nj nk b">try…catch</code>:</p><pre class="kg kh ki kj gt nl nk nm nn aw no bi"><span id="8dda" class="np ml iq nk b gy nq nr l ns nt">function callback() {</span><span id="c333" class="np ml iq nk b gy nu nr l ns nt">   try {<br/>     // error code <br/>   }catch<br/>     console.log("Error caught") ;<br/>   }</span><span id="4e08" class="np ml iq nk b gy nu nr l ns nt">}</span><span id="1d2b" class="np ml iq nk b gy nu nr l ns nt">function test() {</span><span id="6de4" class="np ml iq nk b gy nu nr l ns nt"><strong class="nk ir">      setTimeout(callback, 1000);</strong></span><span id="367b" class="np ml iq nk b gy nu nr l ns nt">}</span></pre><h1 id="540f" class="mk ml iq bd mm mn mo mp mq mr ms mt mu jw mv jx mw jz mx ka my kc mz kd na nb bi translated">5.添加全局错误处理程序</h1><p id="6d00" class="pw-post-body-paragraph kw kx iq ky b kz nc jr lb lc nd ju le lf ne lh li lj nf ll lm ln ng lp lq lr ij bi translated">我们可以注册一个<code class="fe nh ni nj nk b">window.onerror</code>事件监听器，它将在出现未被捕获的错误时运行。这不会处理错误，但会检测到错误——您需要在其中提供自己的<code class="fe nh ni nj nk b">try…catch</code>。</p><pre class="kg kh ki kj gt nl nk nm nn aw no bi"><span id="6d21" class="np ml iq nk b gy nq nr l ns nt">window.onerror = function(e) {</span><span id="6791" class="np ml iq nk b gy nu nr l ns nt">   console.log("error handled", e);</span><span id="fc5d" class="np ml iq nk b gy nu nr l ns nt">}</span><span id="7684" class="np ml iq nk b gy nu nr l ns nt">function funcWithError() {</span><span id="2c03" class="np ml iq nk b gy nu nr l ns nt">    <strong class="nk ir">a; // a is not defined</strong></span><span id="8ffc" class="np ml iq nk b gy nu nr l ns nt">}</span><span id="da35" class="np ml iq nk b gy nu nr l ns nt">function test() {</span><span id="f523" class="np ml iq nk b gy nu nr l ns nt">    <strong class="nk ir">funcWithError();</strong></span><span id="ca70" class="np ml iq nk b gy nu nr l ns nt"><strong class="nk ir">    console.log("hi"); // this will not be executed</strong></span><span id="5d3f" class="np ml iq nk b gy nu nr l ns nt">}</span><span id="81ad" class="np ml iq nk b gy nu nr l ns nt">test(); </span></pre><p id="c4c1" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">跟随Javascript Jeep🚙💨。</p><div class="ls lt gp gr lu lv"><a rel="noopener  ugc nofollow" target="_blank" href="/learn-bigint-in-javascript-df9b61bc19ef"><div class="lw ab fo"><div class="lx ab ly cl cj lz"><h2 class="bd ir gy z fp ma fr fs mb fu fw ip bi translated">学习JavaScript中的BigInt</h2><div class="mc l"><h3 class="bd b gy z fp ma fr fs mb fu fw dk translated">了解如何在JavaScript中使用BigInt存储大数。</h3></div><div class="md l"><p class="bd b dl z fp ma fr fs mb fu fw dk translated">levelup.gitconnected.com</p></div></div><div class="me l"><div class="nx l mg mh mi me mj kp lv"/></div></div></a></div><div class="ls lt gp gr lu lv"><a href="https://medium.com/javascript-in-plain-english/understand-the-superpower-of-optional-chaining-in-javascript-fbc569244471" rel="noopener follow" target="_blank"><div class="lw ab fo"><div class="lx ab ly cl cj lz"><h2 class="bd ir gy z fp ma fr fs mb fu fw ip bi translated">理解JavaScript中可选链接的强大功能</h2><div class="mc l"><h3 class="bd b gy z fp ma fr fs mb fu fw dk translated">了解如何使用即将推出的JavaScript特性可选链接</h3></div><div class="md l"><p class="bd b dl z fp ma fr fs mb fu fw dk translated">medium.com</p></div></div><div class="me l"><div class="ny l mg mh mi me mj kp lv"/></div></div></a></div></div></div>    
</body>
</html>