<html>
<head>
<title>Organize Code with Python Functions — Global Variables and Exceptions</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">使用Python函数组织代码-全局变量和异常</h1>
<blockquote>原文：<a href="https://levelup.gitconnected.com/organize-code-with-python-functions-global-variables-and-exceptions-fa984dddfada?source=collection_archive---------10-----------------------#2020-03-03">https://levelup.gitconnected.com/organize-code-with-python-functions-global-variables-and-exceptions-fa984dddfada?source=collection_archive---------10-----------------------#2020-03-03</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><figure class="gl gn jr js jt ju gh gi paragraph-image"><div role="button" tabindex="0" class="jv jw di jx bf jy"><div class="gh gi jq"><img src="../Images/45dcb9d2fd698dae9b3e9da1ed81f750.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*rl1N1nXpJXTRlzAI"/></div></div><figcaption class="kb kc gj gh gi kd ke bd b be z dk translated">由<a class="ae kf" href="https://unsplash.com/@louishansel?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Louis Hansel @ shotsoflouis</a>在<a class="ae kf" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄的照片</figcaption></figure><p id="cc93" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">Python是一种方便的语言，通常用于脚本编写、数据科学和web开发。</p><p id="a1f2" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在本文中，我们将看看如何用关键字<code class="fe le lf lg lh b">global</code>在函数中定义全局变量并处理异常。</p><h1 id="d59d" class="li lj it bd lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf bi translated">全球声明</h1><p id="b2cc" class="pw-post-body-paragraph kg kh it ki b kj mg kl km kn mh kp kq kr mi kt ku kv mj kx ky kz mk lb lc ld im bi translated">关键字<code class="fe le lf lg lh b">global</code>让我们可以在任何地方定义全局变量。例如，我们可以如下使用它:</p><pre class="ml mm mn mo gt mp lh mq mr aw ms bi"><span id="c056" class="mt lj it lh b gy mu mv l mw mx">def foo():<br/>  global x<br/>  x = 1<br/>foo()<br/>print(x)</span></pre><p id="9b94" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">上面的代码有<code class="fe le lf lg lh b">foo</code>函数，用<code class="fe le lf lg lh b">global x</code>行定义全局变量<code class="fe le lf lg lh b">x</code>。</p><p id="d7fa" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">然后我们把<code class="fe le lf lg lh b">x</code>赋值为1。</p><p id="85b3" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">然后在我们调用<code class="fe le lf lg lh b">foo</code>之后，我们可以访问最后一行的<code class="fe le lf lg lh b">x</code>，因为我们用函数调用声明了全局变量<code class="fe le lf lg lh b">x</code>。</p><p id="1970" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">它们在被定义后必须被引用。</p><p id="4142" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">所以如下:</p><pre class="ml mm mn mo gt mp lh mq mr aw ms bi"><span id="7cff" class="mt lj it lh b gy mu mv l mw mx">print(x)<br/>def foo():<br/>  global x<br/>  x = 1<br/>foo()</span></pre><p id="5cc8" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">会给我们一个错误，说<code class="fe le lf lg lh b">'x'</code>未定义。</p><h1 id="78ac" class="li lj it bd lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf bi translated">异常处理</h1><p id="0fde" class="pw-post-body-paragraph kg kh it ki b kj mg kl km kn mh kp kq kr mi kt ku kv mj kx ky kz mk lb lc ld im bi translated">我们可以一起使用<code class="fe le lf lg lh b">try</code>和<code class="fe le lf lg lh b">except</code>关键字来处理由某些代码段引发的错误。</p><p id="cb5e" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们所要做的就是用<code class="fe le lf lg lh b">try</code>和<code class="fe le lf lg lh b">except</code>包围一段引发错误的代码。然后在<code class="fe le lf lg lh b">except</code>之后，我们运行代码来处理错误。</p><p id="7c36" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">例如，我们可以用它来捕捉除以零的错误，如下所示:</p><pre class="ml mm mn mo gt mp lh mq mr aw ms bi"><span id="411f" class="mt lj it lh b gy mu mv l mw mx">def divide(dividend, divisor):<br/>  try:<br/>    return dividend / divisor<br/>  except ZeroDivisionError:<br/>    print("Can't divide by 0")</span><span id="a988" class="mt lj it lh b gy my mv l mw mx">divide(1, 0)</span></pre><p id="a766" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">当我们在<code class="fe le lf lg lh b">divisor</code>设置为0的情况下调用<code class="fe le lf lg lh b">divide</code>函数时，我们会看到<code class="fe le lf lg lh b">'Can't divide by 0'</code>消息，而不是返回被<code class="fe le lf lg lh b">divisor.</code>除的<code class="fe le lf lg lh b">dividend</code></p><p id="844b" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果我们用一个非零除数调用它，我们得到的是<code class="fe le lf lg lh b">divisor</code>除以<code class="fe le lf lg lh b">dividend</code>。</p><p id="63e8" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们还可以使用<code class="fe le lf lg lh b">except</code>块来捕捉多种错误。</p><p id="2388" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">例如，我们可以这样做:</p><pre class="ml mm mn mo gt mp lh mq mr aw ms bi"><span id="b6fd" class="mt lj it lh b gy mu mv l mw mx">try:<br/>  num = int(input("Please enter a number: "))<br/>except (RuntimeError, TypeError, NameError, ValueError):<br/>  print("Not a number")</span></pre><p id="2c98" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">上面的代码捕捉到了<code class="fe le lf lg lh b">RuntimeError</code>、<code class="fe le lf lg lh b">TypeError</code>、<code class="fe le lf lg lh b">NameError</code>和<code class="fe le lf lg lh b">ValueError</code>。</p><h1 id="a914" class="li lj it bd lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf bi translated">引发异常</h1><p id="8913" class="pw-post-body-paragraph kg kh it ki b kj mg kl km kn mh kp kq kr mi kt ku kv mj kx ky kz mk lb lc ld im bi translated">我们也可以用关键字<code class="fe le lf lg lh b">raise</code>在代码中引发异常。</p><p id="4176" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">例如，我们可以编写以下代码来引发代码中的异常:</p><pre class="ml mm mn mo gt mp lh mq mr aw ms bi"><span id="1263" class="mt lj it lh b gy mu mv l mw mx">try:<br/>  name = input("Please enter a name: ")<br/>  if name != 'Jane':<br/>    raise ValueError<br/>except ValueError:<br/>  print("You're not Jane")</span></pre><p id="b12e" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果<code class="fe le lf lg lh b">name</code>的值不是<code class="fe le lf lg lh b">'Jane'</code>，代码使用<code class="fe le lf lg lh b">raise</code>关键字来引发一个<code class="fe le lf lg lh b">ValueError</code>。</p><p id="6842" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">然后我们在<code class="fe le lf lg lh b">except</code>街区抓住它。</p><figure class="ml mm mn mo gt ju gh gi paragraph-image"><div role="button" tabindex="0" class="jv jw di jx bf jy"><div class="gh gi mz"><img src="../Images/f2f415ec47a9fa890f38bba4b2318971.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*HrKFPdBQwECr3um0"/></div></div><figcaption class="kb kc gj gh gi kd ke bd b be z dk translated">照片由<a class="ae kf" href="https://unsplash.com/@creativegangsters?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">艾莉·史密斯</a>在<a class="ae kf" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄</figcaption></figure><h1 id="94b1" class="li lj it bd lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf bi translated">创造我们自己的例外</h1><p id="21c9" class="pw-post-body-paragraph kg kh it ki b kj mg kl km kn mh kp kq kr mi kt ku kv mj kx ky kz mk lb lc ld im bi translated">我们可以通过扩展<code class="fe le lf lg lh b">Exception</code>类来创建自己的异常类。</p><p id="44ac" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果一个异常类与给定的异常类是同一个类或基类，那么它就是兼容的。</p><p id="8d13" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">例如，我们可以创建自己的<code class="fe le lf lg lh b">FooError</code>类，如下所示:</p><pre class="ml mm mn mo gt mp lh mq mr aw ms bi"><span id="8234" class="mt lj it lh b gy mu mv l mw mx">class FooError(Exception):<br/>  pass</span><span id="534a" class="mt lj it lh b gy my mv l mw mx">try:<br/>  raise FooError     <br/>except FooError:<br/>  print("Foo error")</span></pre><p id="fe8a" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在上面的代码中，我们创建了一个从<code class="fe le lf lg lh b">Exception</code>类派生的<code class="fe le lf lg lh b">FooError</code>类。</p><p id="baeb" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">然后我们像处理内置错误一样使用它。</p><h1 id="2f22" class="li lj it bd lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf bi translated">定义清理活动</h1><p id="006f" class="pw-post-body-paragraph kg kh it ki b kj mg kl km kn mh kp kq kr mi kt ku kv mj kx ky kz mk lb lc ld im bi translated">我们可以使用<code class="fe le lf lg lh b">finally</code>块来运行任何清理代码，不管是否抛出异常。</p><p id="99e6" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">例如，我们可以编写以下代码，在出现异常后打印一条消息:</p><pre class="ml mm mn mo gt mp lh mq mr aw ms bi"><span id="b10c" class="mt lj it lh b gy mu mv l mw mx">try:<br/>  raise ValueError<br/>finally:<br/>  print('Goodbye, world!')</span></pre><p id="6689" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们看到<code class="fe le lf lg lh b">‘Goodbye, world!’</code>显示，即使在<code class="fe le lf lg lh b">ValueError</code>升高之后。</p><h1 id="4fbb" class="li lj it bd lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf bi translated">预定义的清理操作</h1><p id="502d" class="pw-post-body-paragraph kg kh it ki b kj mg kl km kn mh kp kq kr mi kt ku kv mj kx ky kz mk lb lc ld im bi translated">一些对象有标准的清理动作。我们可以用关键字<code class="fe le lf lg lh b">with</code>运行这些函数。</p><p id="0875" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">例如，打开文件的<code class="fe le lf lg lh b">open</code>函数具有预定义的清除动作。</p><p id="66c7" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">例如，我们可以如下调用<code class="fe le lf lg lh b">open</code>函数:</p><pre class="ml mm mn mo gt mp lh mq mr aw ms bi"><span id="28f8" class="mt lj it lh b gy mu mv l mw mx">with open("foo.txt") as f:<br/>  for line in f:<br/>    print(line, end="")</span></pre><p id="31cb" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">那我们就不用写什么清理代码了。</p><h1 id="606e" class="li lj it bd lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf bi translated">结论</h1><p id="6a12" class="pw-post-body-paragraph kg kh it ki b kj mg kl km kn mh kp kq kr mi kt ku kv mj kx ky kz mk lb lc ld im bi translated">我们可以用<code class="fe le lf lg lh b">global</code>关键字在任何地方定义全局变量。</p><p id="bf68" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">为了捕捉异常，我们用<code class="fe le lf lg lh b">try</code>和<code class="fe le lf lg lh b">except</code>包围可能引发异常的代码。</p><p id="0620" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们可以使用<code class="fe le lf lg lh b">raise</code>关键字引发异常。为了创建我们自己的类，我们可以创建一个继承自<code class="fe le lf lg lh b">Exception</code>的类。</p><p id="12ae" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">为了运行清理代码而不管是否抛出异常，我们可以使用<code class="fe le lf lg lh b">finally</code>块。</p><p id="946b" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">像<code class="fe le lf lg lh b">open</code>这样的功能已经预定义了清理动作。我们可以使用<code class="fe le lf lg lh b">with</code>语句在没有<code class="fe le lf lg lh b">finally</code>的情况下运行带有清理动作的那些函数。</p></div></div>    
</body>
</html>