<html>
<head>
<title>Creating Taboo Error Handler for Go</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">为Go创建禁忌错误处理程序</h1>
<blockquote>原文：<a href="https://levelup.gitconnected.com/creating-taboo-error-handler-for-go-e1bd337a4e7e?source=collection_archive---------10-----------------------#2020-10-31">https://levelup.gitconnected.com/creating-taboo-error-handler-for-go-e1bd337a4e7e?source=collection_archive---------10-----------------------#2020-10-31</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><figure class="gl gn jr js jt ju gh gi paragraph-image"><div role="button" tabindex="0" class="jv jw di jx bf jy"><div class="gh gi jq"><img src="../Images/e8e4c74f5e5a5317e8af65b0d9e771f0.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*pLYCry7RgUMJH9NJ"/></div></div><figcaption class="kb kc gj gh gi kd ke bd b be z dk translated"><em class="kf">Unsplash上@hhh13的照片</em></figcaption></figure><p id="03c4" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我为Golang创建了<a class="ae le" href="https://github.com/anon-org/taboo" rel="noopener ugc nofollow" target="_blank">这个模块</a>来帮助我处理错误。当我的一个同事考虑将<code class="fe lf lg lh li b">context</code>从处理程序传递给服务，传递给存储库以更详细地跟踪错误日志时，这个想法就出现了。我不同意他的观点，因为我认为那不是<code class="fe lf lg lh li b">context</code>的目的。也许是我错了，或者是他错了，或者是我们都错了，因为这是我们第一个投入生产的Golang项目。</p><p id="d4eb" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">尽管我们对<code class="fe lf lg lh li b">context</code>有不同的看法，但我们都认为Golang的错误处理过于冗长和庞大。它让我们阅读更多的错误处理，而不是系统流程本身。然后我记得当我使用Java/Kotlin编码时，我总是使用<code class="fe lf lg lh li b">throws</code>、<code class="fe lf lg lh li b">throw</code>和<code class="fe lf lg lh li b">try-catch block</code>来处理任何错误。</p><p id="ffb1" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">嗯…</p><p id="01fc" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我为什么不为Golang创作呢？</p><p id="04ef" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">然后我为Golang创建了这个名为<code class="fe lf lg lh li b">taboo</code>的<code class="fe lf lg lh li b">try-catch block</code>模块。因为我知道这个东西在Golang开发者中引起争论，但是，那我想我为什么不试一试呢？</p><p id="f14b" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">对于设计本身，我的灵感来自于<a class="ae le" href="https://hackthology.com/exceptions-for-go-as-a-library.html" rel="noopener ugc nofollow" target="_blank">这篇文章</a>，但整个实现都是根据我当前的需求进行调整的。这个模块不是基于<code class="fe lf lg lh li b">error</code>，而是基于<code class="fe lf lg lh li b">panic</code>和<code class="fe lf lg lh li b">recover</code>，所以只要在错误的条件下使用，就会非常危险。</p><p id="60fc" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">让我们举个例子:</p><pre class="lj lk ll lm gt ln li lo lp aw lq bi"><span id="e1fd" class="lr ls it li b gy lt lu l lv lw">package main</span><span id="146d" class="lr ls it li b gy lx lu l lv lw">func div(a, b int) int {<br/>  return a / b<br/>}</span><span id="72de" class="lr ls it li b gy lx lu l lv lw">func main() {<br/>  div(10, 0)<br/>}</span></pre><p id="6bc4" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">当<code class="fe lf lg lh li b">b</code>被<code class="fe lf lg lh li b">zero</code>填满时，会引起恐慌</p><pre class="lj lk ll lm gt ln li lo lp aw lq bi"><span id="4c92" class="lr ls it li b gy lt lu l lv lw">panic: runtime error: integer divide by zero</span><span id="baca" class="lr ls it li b gy lx lu l lv lw">goroutine 1 [running]:<br/>main.div(...)<br/>        /tmp/anon-org/taboo/cmd/example.go:4<br/>main.main()<br/>        /tmp/anon-org/taboo/cmd/example.go:8 +0x12</span><span id="e53d" class="lr ls it li b gy lx lu l lv lw">Process finished with exit code 2</span></pre><p id="8df8" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">因此，我们可以像这样使用<code class="fe lf lg lh li b">taboo</code>来处理它:</p><pre class="lj lk ll lm gt ln li lo lp aw lq bi"><span id="116a" class="lr ls it li b gy lt lu l lv lw">taboo.Try(func() {<br/>  div(10, 0)  <br/>}).Catch(func(e *taboo.Exception) {<br/>  fmt.Println(e.Error())<br/>}).Do()</span></pre><p id="ab09" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><code class="fe lf lg lh li b">taboo</code>将捕获<code class="fe lf lg lh li b">panic</code>并尝试<code class="fe lf lg lh li b">recover</code>它，并生成一个名为<code class="fe lf lg lh li b">taboo.Exception</code>的错误堆栈，以便更详细地跟踪错误。所以程序是这样结束的:</p><pre class="lj lk ll lm gt ln li lo lp aw lq bi"><span id="6e88" class="lr ls it li b gy lt lu l lv lw">main.div:9 runtime error: integer divide by zero</span><span id="2ac4" class="lr ls it li b gy lx lu l lv lw">Process finished with exit code 0</span></pre><p id="93e6" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">很方便吧？</p><p id="7b9e" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">那么，如果我想将错误抛出或再次抛出给第一个调用者呢？</p><pre class="lj lk ll lm gt ln li lo lp aw lq bi"><span id="de88" class="lr ls it li b gy lt lu l lv lw">package main</span><span id="9b04" class="lr ls it li b gy lx lu l lv lw">import (<br/>  "errors"<br/>  "fmt"<br/>  "github.com/anon-org/taboo/pkg/taboo"<br/>)</span><span id="58ea" class="lr ls it li b gy lx lu l lv lw">func div(a, b int) int {<br/>  if b == 0 {<br/>    taboo.Throw(errors.New("division by zero detected"))<br/>  }<br/>  return a / b<br/>}</span><span id="df77" class="lr ls it li b gy lx lu l lv lw">func callDiv() int {<br/>  var result int</span><span id="bbcb" class="lr ls it li b gy lx lu l lv lw">taboo.Try(func() {<br/>    result = div(10, 0)<br/>  }).Catch(func(e *taboo.Exception) {<br/>    e.Throw("callDiv rethrow this error")<br/>  }).Do()</span><span id="4840" class="lr ls it li b gy lx lu l lv lw">return result<br/>}</span><span id="7cf7" class="lr ls it li b gy lx lu l lv lw">func callCallDiv() int {<br/>  var result int</span><span id="be98" class="lr ls it li b gy lx lu l lv lw">taboo.Try(func() {<br/>    result = callDiv()<br/>  }).Catch(func(e *taboo.Exception) {<br/>    e.Throw("callCallDiv rethrow this error")<br/>  }).Do()</span><span id="10c7" class="lr ls it li b gy lx lu l lv lw">return result<br/>}</span><span id="bad4" class="lr ls it li b gy lx lu l lv lw">func main() {<br/>  taboo.Try(func() {<br/>    callCallDiv()<br/>  }).Catch(func(e *taboo.Exception) {<br/>    fmt.Println(e.Error())<br/>  }).Do()<br/>}</span></pre><p id="724b" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><code class="fe lf lg lh li b">e.Throw(message)</code>将包装上一个异常，并再次抛出给上一个调用者。所以打印出来的错误会是这样的:</p><pre class="lj lk ll lm gt ln li lo lp aw lq bi"><span id="f12d" class="lr ls it li b gy lt lu l lv lw">main.callCallDiv:34 callCallDiv rethrow this error caused by:<br/>  main.callDiv:22 callDiv rethrow this error caused by:<br/>    main.div:11 division by zero detected<br/><br/>Process finished with exit code 0</span></pre><p id="322b" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我认为它就像Java/Kotlin中的<code class="fe lf lg lh li b">try-catch block</code>,但是有很多缺陷。这个模块仍然是一个实验，我自己不打算在生产中使用这个模块。或者也许我应该？</p></div><div class="ab cl ly lz hx ma" role="separator"><span class="mb bw bk mc md me"/><span class="mb bw bk mc md me"/><span class="mb bw bk mc md"/></div><div class="im in io ip iq"><p id="a9e9" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><em class="mf">最初发布于</em><a class="ae le" href="https://clavinjune.dev/en/blogs/creating-taboo-error-handler-for-go/" rel="noopener ugc nofollow" target="_blank"><em class="mf">https://clavinjune . dev</em></a><em class="mf">。</em></p></div></div>    
</body>
</html>